### PR TITLE
Faster version

### PR DESCRIPTION
**Pull request by howmanysmall**
image

### CODE REVIEW

**Comment by headjoe3** [comment]
Interesting implementation.

How does this affect debug tracebacks/error messages?

**Comment by howmanysmall** [comment]
@Validark made it originally, he would know best. I don't think it affects it at all.

**Comment by headjoe3** [comment]
I'm getting this with the coroutine implementation
image

Where the old implementation errors in the correct location
image

Most of the reason for using FastSpawn instead of coroutine.wrap is that debug tracebacks are more accurate, and link to the user's code, rather than the FastSpawn code. I'm going to close this for now, as I don't think it's worth sacrificing this behavior for the sake of micro-optimization.

**Comment by Validark** [comment]
I agree with headJoe here. I will probably change my implementation to match.

**Pull request closed without merging**
